// client-app/src/pages/admin/Overview.tsx
import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { Row, Col, Card, Statistic, Spin, Alert, List, Typography, Space, Badge } from 'antd';
import {
  UserOutlined, TeamOutlined, BookOutlined, HomeOutlined,
  DollarOutlined, LineChartOutlined, WarningOutlined, CheckCircleOutlined,
} from '@ant-design/icons';
import {
  AreaChart, Area, BarChart, Bar, XAxis, YAxis,
  CartesianGrid, Tooltip, ResponsiveContainer, Legend,
} from 'recharts';
import { dashboardService } from '../../services';

const { Title, Text } = Typography;

export const Overview: React.FC = () => {
  const { data: stats, isLoading, error } = useQuery({
    queryKey: ['dashboardStats'],
    queryFn: dashboardService.getStats,
    refetchInterval: 60000, // refresh every minute
  });

  if (isLoading) {
    return (
      <div style={{ textAlign: 'center', padding: '100px 0' }}>
        <Spin size="large" />
        <div style={{ marginTop: 16, color: '#666' }}>Loading dashboard...</div>
      </div>
    );
  }

  if (error) {
    return (
      <Alert
        message="Error"
        description="Could not load dashboard statistics. Make sure the backend is running."
        type="error"
        showIcon
      />
    );
  }

  const revenueData = stats?.revenueChart ?? [];
  const attendanceData = stats?.attendanceChart ?? [];

  return (
    <div>
      <div style={{ marginBottom: 24 }}>
        <Title level={2} style={{ margin: 0, fontWeight: 700 }}>Admin Dashboard</Title>
        <Text type="secondary">Welcome to SmartEdu management center.</Text>
      </div>

      {/* KPI Row 1 */}
      <Row gutter={[16, 16]} style={{ marginBottom: 24 }}>
        {[
          { title: 'Total Students', value: stats?.totalStudents, icon: <TeamOutlined />, color: '#1890ff' },
          { title: 'Total Teachers', value: stats?.totalTeachers, icon: <UserOutlined />, color: '#52c41a' },
          { title: 'Total Classes', value: stats?.totalClasses, icon: <HomeOutlined />, color: '#722ed1' },
          { title: 'Total Courses', value: stats?.totalCourses, icon: <BookOutlined />, color: '#fa8c16' },
        ].map((kpi) => (
          <Col xs={24} sm={12} md={6} key={kpi.title}>
            <Card hoverable style={{ borderTop: `3px solid ${kpi.color}` }}>
              <Statistic
                title={kpi.title}
                value={kpi.value ?? 0}
                prefix={React.cloneElement(kpi.icon as React.ReactElement<{ style?: React.CSSProperties }>, { style: { color: kpi.color, marginRight: 8 } })}
              />
            </Card>
          </Col>
        ))}
      </Row>

      {/* KPI Row 2 */}
      <Row gutter={[16, 16]} style={{ marginBottom: 24 }}>
        <Col xs={24} sm={12} md={6}>
          <Card hoverable style={{ borderTop: '3px solid #13c2c2' }}>
            <Statistic
              title="Monthly Revenue"
              value={stats?.monthlyRevenue ?? 0}
              precision={0}
              suffix="VND"
              prefix={<DollarOutlined style={{ color: '#13c2c2', marginRight: 8 }} />}
              formatter={(v) => Number(v).toLocaleString('vi-VN')}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} md={6}>
          <Card hoverable style={{ borderTop: '3px solid #eb2f96' }}>
            <Statistic
              title="Today's Attendance"
              value={stats?.todayAttendance ?? 0}
              prefix={<LineChartOutlined style={{ color: '#eb2f96', marginRight: 8 }} />}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} md={6}>
          <Card hoverable style={{ borderTop: '3px solid #52c41a' }}>
            <Statistic
              title="Active Students"
              value={stats?.activeStudents ?? 0}
              prefix={<CheckCircleOutlined style={{ color: '#52c41a', marginRight: 8 }} />}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} md={6}>
          <Card hoverable style={{ borderTop: '3px solid #faad14' }}>
            <Statistic
              title="Pending Absence Requests"
              value={stats?.pendingAbsenceRequests ?? 0}
              prefix={<WarningOutlined style={{ color: '#faad14', marginRight: 8 }} />}
              valueStyle={{ color: (stats?.pendingAbsenceRequests ?? 0) > 0 ? '#faad14' : 'inherit' }}
            />
          </Card>
        </Col>
      </Row>

      {/* Charts */}
      <Row gutter={[24, 24]} style={{ marginBottom: 24 }}>
        <Col xs={24} lg={14}>
          <Card title="Revenue — Last 6 Months" style={{ borderRadius: 8 }}>
            <div style={{ width: '100%', height: 300 }}>
              {revenueData.length === 0 ? (
                <div style={{ textAlign: 'center', paddingTop: 100 }}>
                  <Text type="secondary">No revenue data available yet.</Text>
                </div>
              ) : (
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={revenueData}>
                    <defs>
                      <linearGradient id="colorRevenue" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#1890ff" stopOpacity={0.8} />
                        <stop offset="95%" stopColor="#1890ff" stopOpacity={0} />
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis dataKey="month" />
                    <YAxis tickFormatter={(v) => `${(v / 1000000).toFixed(1)}M`} />
                    <Tooltip formatter={(v) => [`${Number(v).toLocaleString('vi-VN')} VND`, 'Revenue']} />
                    <Area type="monotone" dataKey="revenue" stroke="#1890ff" fillOpacity={1} fill="url(#colorRevenue)" />
                  </AreaChart>
                </ResponsiveContainer>
              )}
            </div>
          </Card>
        </Col>
        <Col xs={24} lg={10}>
          <Card title="Attendance — Last 7 Days" style={{ borderRadius: 8 }}>
            <div style={{ width: '100%', height: 300 }}>
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={attendanceData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="date" />
                  <YAxis />
                  <Tooltip />
                  <Legend />
                  <Bar dataKey="present" fill="#52c41a" name="Present" radius={[4, 4, 0, 0]} />
                  <Bar dataKey="absent" fill="#ff4d4f" name="Absent" radius={[4, 4, 0, 0]} />
                  <Bar dataKey="late" fill="#faad14" name="Late" radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </Card>
        </Col>
      </Row>

      {/* Business Rules Notice */}
      <Card title="Active Business Rules" style={{ borderRadius: 8 }}>
        <List
          grid={{ gutter: 16, column: 2 }}
          dataSource={[
            'Attendance marked Present → Auto-deduct wallet',
            'Unexcused Absence → Auto-deduct wallet',
            'Excused Absence → No deduction',
            'Duplicate deduction prevented via IsDeducted flag',
            'Daily job: warn wallets < 3 sessions or < 500,000 VND',
            'Student transfer preserves remaining sessions',
          ]}
          renderItem={(item) => (
            <List.Item>
              <Space>
                <Badge status="success" />
                <Text>{item}</Text>
              </Space>
            </List.Item>
          )}
        />
      </Card>
    </div>
  );
};

// new-client-app/src/app/pages/admin/overview/overview.component.ts
import { Component, OnInit, ViewChild, ElementRef, signal, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DashboardService } from '../../../core/services/dashboard.service';
import { DashboardStatsDto } from '../../../core/models';
import { Chart, registerables } from 'chart.js';

Chart.register(...registerables);

@Component({
  selector: 'app-overview',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './overview.component.html',
  styleUrl: './overview.component.css'
})
export class OverviewComponent implements OnInit, OnDestroy {
  stats = signal<DashboardStatsDto | null>(null);
  loading = signal<boolean>(true);
  error = signal<string | null>(null);

  kpiRow1 = signal<any[]>([]);

  @ViewChild('revenueCanvas') revenueCanvas!: ElementRef<HTMLCanvasElement>;
  @ViewChild('attendanceCanvas') attendanceCanvas!: ElementRef<HTMLCanvasElement>;

  revenueChartInstance: Chart | null = null;
  attendanceChartInstance: Chart | null = null;

  rules = [
    'Attendance marked Present → Auto-deduct wallet',
    'Unexcused Absence → Auto-deduct wallet',
    'Excused Absence → No deduction',
    'Duplicate deduction prevented via IsDeducted flag',
    'Daily job: warn wallets < 3 sessions or < 500,000 VND',
    'Student transfer preserves remaining sessions'
  ];

  private pollInterval: any;

  constructor(private dashboardService: DashboardService) {}

  ngOnInit() {
    this.loadStats();
    this.pollInterval = setInterval(() => this.loadStats(false), 60000);
  }

  ngOnDestroy() {
    if (this.pollInterval) clearInterval(this.pollInterval);
    this.destroyCharts();
  }

  loadStats(showSpinner = true) {
    if (showSpinner) this.loading.set(true);
    this.error.set(null);

    this.dashboardService.getStats().subscribe({
      next: (data) => {
        this.stats.set(data);
        this.loading.set(false);
        this.updateKPIs(data);
        // Delay to let ViewChild bindings resolve after rendering
        setTimeout(() => this.initCharts(data), 50);
      },
      error: (err) => {
        this.loading.set(false);
        this.error.set('Could not load dashboard statistics. Make sure the backend is running.');
        console.error(err);
      }
    });
  }

  updateKPIs(data: DashboardStatsDto) {
    this.kpiRow1.set([
      { title: 'Total Students', value: data.totalStudents, icon: 'bi bi-people', color: '#1890ff' },
      { title: 'Total Teachers', value: data.totalTeachers, icon: 'bi bi-person-badge', color: '#52c41a' },
      { title: 'Total Classes', value: data.totalClasses, icon: 'bi bi-building', color: '#722ed1' },
      { title: 'Total Courses', value: data.totalCourses, icon: 'bi bi-book', color: '#fa8c16' }
    ]);
  }

  destroyCharts() {
    if (this.revenueChartInstance) {
      this.revenueChartInstance.destroy();
      this.revenueChartInstance = null;
    }
    if (this.attendanceChartInstance) {
      this.attendanceChartInstance.destroy();
      this.attendanceChartInstance = null;
    }
  }

  initCharts(data: DashboardStatsDto) {
    this.destroyCharts();

    const revenueData = data.revenueChart || [];
    const attendanceData = data.attendanceChart || [];

    // Initialize Revenue Area Chart
    if (this.revenueCanvas && revenueData.length > 0) {
      const ctx = this.revenueCanvas.nativeElement.getContext('2d');
      if (ctx) {
        // Create blue gradient
        const gradient = ctx.createLinearGradient(0, 0, 0, 300);
        gradient.addColorStop(0, 'rgba(24, 144, 255, 0.4)');
        gradient.addColorStop(1, 'rgba(24, 144, 255, 0)');

        this.revenueChartInstance = new Chart(this.revenueCanvas.nativeElement, {
          type: 'line',
          data: {
            labels: revenueData.map(item => item.month),
            datasets: [{
              label: 'Revenue (VND)',
              data: revenueData.map(item => item.revenue),
              borderColor: '#1890ff',
              borderWidth: 2,
              fill: true,
              backgroundColor: gradient,
              tension: 0.3
            }]
          },
          options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
              legend: { display: false }
            },
            scales: {
              y: {
                beginAtZero: true,
                ticks: {
                  callback: (value) => {
                    return (Number(value) / 1000000).toFixed(1) + 'M';
                  }
                }
              }
            }
          }
        });
      }
    }

    // Initialize Attendance Bar Chart
    if (this.attendanceCanvas && attendanceData.length > 0) {
      this.attendanceChartInstance = new Chart(this.attendanceCanvas.nativeElement, {
        type: 'bar',
        data: {
          labels: attendanceData.map(item => item.date),
          datasets: [
            {
              label: 'Present',
              data: attendanceData.map(item => item.present),
              backgroundColor: '#52c41a',
              borderRadius: 4
            },
            {
              label: 'Absent',
              data: attendanceData.map(item => item.absent),
              backgroundColor: '#ff4d4f',
              borderRadius: 4
            },
            {
              label: 'Late',
              data: attendanceData.map(item => item.late),
              backgroundColor: '#faad14',
              borderRadius: 4
            }
          ]
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          plugins: {
            legend: { position: 'bottom' }
          },
          scales: {
            x: { stacked: false },
            y: { stacked: false, beginAtZero: true }
          }
        }
      });
    }
  }

  formatCurrency(value?: number): string {
    if (value === undefined || value === null) return '0 VND';
    return value.toLocaleString('vi-VN') + ' VND';
  }
}

<div>
  <!-- Header -->
  <div class="mb-4">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb mb-1" style="font-size: 12px;">
        <li class="breadcrumb-item"><a href="#" class="text-decoration-none text-muted">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Admin Overview</li>
      </ol>
    </nav>
    <h1 class="page-title">Admin Dashboard</h1>
    <p class="text-muted">Welcome to SmartEdu management center.</p>
  </div>

  @if (loading()) {
    <div class="text-center py-5">
      <div class="spinner-border text-primary" role="status"></div>
      <div class="mt-2 text-muted">Loading dashboard...</div>
    </div>
  } @else if (error()) {
    <div class="alert alert-danger" role="alert">
      {{ error() }}
    </div>
  } @else {
    <!-- KPI Row 1 -->
    <div class="row g-4 mb-4">
      @for (kpi of kpiRow1(); track kpi.title) {
        <div class="col-12 col-sm-6 col-md-3">
          <div class="custom-card shadow-sm border-top border-3" [style.border-top-color]="kpi.color" style="margin-bottom: 0;">
            <div class="d-flex align-items-center justify-content-between">
              <div>
                <div class="text-muted small text-uppercase fw-semibold mb-1">{{ kpi.title }}</div>
                <div class="kpi-number" [style.color]="kpi.color">{{ kpi.value }}</div>
              </div>
              <div class="rounded-circle d-flex align-items-center justify-content-center text-white" 
                   [style.background-color]="kpi.color" style="width: 44px; height: 44px; font-size: 20px;">
                <i [class]="kpi.icon"></i>
              </div>
            </div>
          </div>
        </div>
      }
    </div>

    <!-- KPI Row 2 -->
    <div class="row g-4 mb-4">
      <!-- Monthly Revenue -->
      <div class="col-12 col-sm-6 col-md-3">
        <div class="custom-card shadow-sm border-top border-3 border-teal" style="border-top-color: #13c2c2; margin-bottom: 0;">
          <div class="d-flex align-items-center justify-content-between">
            <div>
              <div class="text-muted small text-uppercase fw-semibold mb-1">Monthly Revenue</div>
              <div class="kpi-number text-teal" style="color: #13c2c2; font-size: 22px;">{{ formatCurrency(stats()?.monthlyRevenue) }}</div>
            </div>
            <div class="rounded-circle d-flex align-items-center justify-content-center text-white" 
                 style="background-color: #13c2c2; width: 44px; height: 44px; font-size: 20px;">
              <i class="bi bi-cash-stack"></i>
            </div>
          </div>
        </div>
      </div>

      <!-- Today's Attendance -->
      <div class="col-12 col-sm-6 col-md-3">
        <div class="custom-card shadow-sm border-top border-3 border-pink" style="border-top-color: #eb2f96; margin-bottom: 0;">
          <div class="d-flex align-items-center justify-content-between">
            <div>
              <div class="text-muted small text-uppercase fw-semibold mb-1">Today's Attendance</div>
              <div class="kpi-number" style="color: #eb2f96;">{{ stats()?.todayAttendance ?? 0 }}</div>
            </div>
            <div class="rounded-circle d-flex align-items-center justify-content-center text-white" 
                 style="background-color: #eb2f96; width: 44px; height: 44px; font-size: 20px;">
              <i class="bi bi-journal-check"></i>
            </div>
          </div>
        </div>
      </div>

      <!-- Active Students -->
      <div class="col-12 col-sm-6 col-md-3">
        <div class="custom-card shadow-sm border-top border-3 border-success" style="border-top-color: #52c41a; margin-bottom: 0;">
          <div class="d-flex align-items-center justify-content-between">
            <div>
              <div class="text-muted small text-uppercase fw-semibold mb-1">Active Students</div>
              <div class="kpi-number text-success" style="color: #52c41a;">{{ stats()?.activeStudents ?? 0 }}</div>
            </div>
            <div class="rounded-circle d-flex align-items-center justify-content-center text-white" 
                 style="background-color: #52c41a; width: 44px; height: 44px; font-size: 20px;">
              <i class="bi bi-person-check"></i>
            </div>
          </div>
        </div>
      </div>

      <!-- Pending Absence Requests -->
      <div class="col-12 col-sm-6 col-md-3">
        <div class="custom-card shadow-sm border-top border-3" 
             [style.border-top-color]="(stats()?.pendingAbsenceRequests ?? 0) > 0 ? '#faad14' : '#6c757d'" 
             style="margin-bottom: 0;">
          <div class="d-flex align-items-center justify-content-between">
            <div>
              <div class="text-muted small text-uppercase fw-semibold mb-1">Pending Absences</div>
              <div class="kpi-number" [style.color]="(stats()?.pendingAbsenceRequests ?? 0) > 0 ? '#faad14' : '#6c757d'">
                {{ stats()?.pendingAbsenceRequests ?? 0 }}
              </div>
            </div>
            <div class="rounded-circle d-flex align-items-center justify-content-center text-white" 
                 [style.background-color]="(stats()?.pendingAbsenceRequests ?? 0) > 0 ? '#faad14' : '#6c757d'" 
                 style="width: 44px; height: 44px; font-size: 20px;">
              <i class="bi bi-exclamation-triangle"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Charts Row -->
    <div class="row g-4 mb-4">
      <!-- Revenue Chart -->
      <div class="col-12 col-lg-7">
        <div class="custom-card shadow-sm h-100 mb-0">
          <h5 class="fw-bold mb-3">Revenue — Last 6 Months</h5>
          <div class="chart-container position-relative" style="height: 300px;">
            <canvas #revenueCanvas></canvas>
          </div>
        </div>
      </div>

      <!-- Attendance Chart -->
      <div class="col-12 col-lg-5">
        <div class="custom-card shadow-sm h-100 mb-0">
          <h5 class="fw-bold mb-3">Attendance — Last 7 Days</h5>
          <div class="chart-container position-relative" style="height: 300px;">
            <canvas #attendanceCanvas></canvas>
          </div>
        </div>
      </div>
    </div>

    <!-- Business Rules -->
    <div class="custom-card shadow-sm">
      <h5 class="fw-bold mb-3">Active Business Rules</h5>
      <div class="row g-3">
        @for (rule of rules; track rule) {
          <div class="col-12 col-md-6 d-flex align-items-start gap-2">
            <span class="badge rounded-circle bg-success-subtle text-success p-1" style="font-size: 10px;">
              <i class="bi bi-check-lg"></i>
            </span>
            <span class="text-dark">{{ rule }}</span>
          </div>
        }
      </div>
    </div>
  }
</div>
