// client-app/src/components/DashboardLayout.tsx
import React, { useState } from 'react';
import { Layout, Menu, Button, Avatar, Badge, Popconfirm, theme, Modal, Form, Input, message, Popover, List } from 'antd';
import { Link, useLocation, useNavigate, Outlet } from 'react-router-dom';
import { useAppDispatch, useAppSelector } from '../hooks/redux';
import { logout, updateUserInfo } from '../store/authSlice';
import api from '../services/api';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import dayjs from 'dayjs';
import {
  DashboardOutlined,
  UserOutlined,
  TeamOutlined,
  BookOutlined,
  HomeOutlined,
  CalendarOutlined,
  WalletOutlined,
  FileTextOutlined,
  LogoutOutlined,
  BellOutlined,
  MenuUnfoldOutlined,
  MenuFoldOutlined,
  UploadOutlined,
} from '@ant-design/icons';

const { Header, Sider, Content } = Layout;

export const DashboardLayout: React.FC = () => {
  const [collapsed, setCollapsed] = useState(false);
  const location = useLocation();
  const navigate = useNavigate();
  const dispatch = useAppDispatch();
  const { user } = useAppSelector((state) => state.auth);

  const queryClient = useQueryClient();
  const studentId = user?.studentId;
  const teacherId = user?.teacherId;
  const isStudent = user?.roles?.includes('Student');
  const isTeacher = user?.roles?.includes('Teacher');
  const isAdmin = user?.roles?.includes('Admin');

  const { data: notificationsRes } = useQuery({
    queryKey: ['notifications', studentId, teacherId],
    queryFn: () => {
      if (isStudent && studentId) {
        return api.get(`/notifications/student/${studentId}`).then((res) => res.data);
      }
      if (isTeacher && teacherId) {
        return api.get(`/notifications/teacher/${teacherId}`).then((res) => res.data);
      }
      return Promise.resolve({ data: [] });
    },
    enabled: !!(studentId || teacherId),
    refetchInterval: 15000,
  });

  const notifications = notificationsRes?.data || [];
  const unreadCount = notifications.filter((n: any) => !n.isRead).length;

  const handleMarkAsRead = async (id: number) => {
    try {
      await api.put(`/notifications/${id}/read`);
      queryClient.invalidateQueries({ queryKey: ['notifications'] });
    } catch (err) {
      message.error('Failed to mark notification as read');
    }
  };

  const notificationContent = (
    <div style={{ width: 320, maxHeight: 400, overflowY: 'auto' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8, paddingBottom: 8, borderBottom: '1px solid #f0f0f0' }}>
        <span style={{ fontWeight: 600 }}>Thông báo</span>
        {unreadCount > 0 && (
          <Button
            type="link"
            size="small"
            style={{ padding: 0 }}
            onClick={async () => {
              try {
                const unreadNotifications = notifications.filter((n: any) => !n.isRead);
                await Promise.all(unreadNotifications.map((n: any) => api.put(`/notifications/${n.id}/read`)));
                queryClient.invalidateQueries({ queryKey: ['notifications'] });
                message.success('Đã đọc tất cả thông báo');
              } catch (err) {
                message.error('Thao tác thất bại');
              }
            }}
          >
            Đọc tất cả
          </Button>
        )}
      </div>
      {notifications.length === 0 ? (
        <div style={{ textAlign: 'center', padding: '24px 0', color: '#8c8c8c' }}>
          Không có thông báo nào
        </div>
      ) : (
        <List
          dataSource={notifications}
          renderItem={(item: any) => (
            <List.Item
              style={{
                padding: '8px 8px',
                backgroundColor: item.isRead ? 'transparent' : '#f0f5ff',
                cursor: 'pointer',
                borderRadius: 4,
                marginBottom: 4,
                display: 'block',
              }}
              onClick={() => {
                if (!item.isRead) {
                  handleMarkAsRead(item.id);
                }
              }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                <span style={{ fontWeight: item.isRead ? 500 : 700, fontSize: 13, color: '#262626' }}>
                  {item.title}
                </span>
                <span style={{ fontSize: 11, color: '#8c8c8c' }}>
                  {dayjs(item.sentAt).format('HH:mm DD/MM')}
                </span>
              </div>
              <div style={{ fontSize: 12, color: '#595959', marginTop: 4 }}>
                {item.message}
              </div>
            </List.Item>
          )}
        />
      )}
    </div>
  );

  const [profileModalOpen, setProfileModalOpen] = useState(false);
  const [profileForm] = Form.useForm();
  const [avatarPreview, setAvatarPreview] = useState<string>('');
  const [uploading, setUploading] = useState(false);

  const handleOpenProfileModal = () => {
    setAvatarPreview(user?.avatarUrl || '');
    profileForm.setFieldsValue({
      fullName: user?.fullName || '',
      phone: user?.phone || '',
      avatarUrl: user?.avatarUrl || '',
      password: '',
    });
    setProfileModalOpen(true);
  };

  const handleAvatarChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const formData = new FormData();
    formData.append('file', file);

    setUploading(true);
    try {
      const res = await api.post('/upload', formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });
      const fileUrl = res.data.data;
      setAvatarPreview(fileUrl);
      profileForm.setFieldsValue({ avatarUrl: fileUrl });
      message.success('Avatar uploaded successfully');
    } catch (err) {
      message.error('Failed to upload avatar');
    } finally {
      setUploading(false);
    }
  };

  const handleProfileSubmit = () => {
    profileForm.validateFields().then(async (values) => {
      try {
        const res = await api.put('/auth/profile', values);
        dispatch(updateUserInfo(res.data.data));
        message.success('Profile updated successfully');
        setProfileModalOpen(false);
      } catch (err: any) {
        message.error(err.response?.data?.message || 'Failed to update profile');
      }
    });
  };
  
  const {
    token: { colorBgContainer, borderRadiusLG },
  } = theme.useToken();

  const handleLogout = () => {
    dispatch(logout());
    navigate('/login');
  };



  // Define sidebar menu items based on roles
  const getMenuItems = () => {
    if (isAdmin) {
      return [
        {
          key: '/admin',
          icon: <DashboardOutlined />,
          label: <Link to="/admin">Overview</Link>,
        },
        {
          key: '/admin/students',
          icon: <TeamOutlined />,
          label: <Link to="/admin/students">Students</Link>,
        },
        {
          key: '/admin/teachers',
          icon: <UserOutlined />,
          label: <Link to="/admin/teachers">Teachers</Link>,
        },
        {
          key: '/admin/courses',
          icon: <BookOutlined />,
          label: <Link to="/admin/courses">Courses</Link>,
        },
        {
          key: '/admin/classes',
          icon: <HomeOutlined />,
          label: <Link to="/admin/classes">Classes</Link>,
        },
        {
          key: '/admin/reports',
          icon: <FileTextOutlined />,
          label: <Link to="/admin/reports">Reports</Link>,
        },
      ];
    } else if (isStudent) {
      return [
        {
          key: '/student',
          icon: <DashboardOutlined />,
          label: <Link to="/student">Dashboard</Link>,
        },
        {
          key: '/student/schedule',
          icon: <CalendarOutlined />,
          label: <Link to="/student/schedule">Schedule</Link>,
        },
        {
          key: '/student/classes',
          icon: <HomeOutlined />,
          label: <Link to="/student/classes">My Classes</Link>,
        },
        {
          key: '/student/tuition',
          icon: <WalletOutlined />,
          label: <Link to="/student/tuition">Tuition Wallet</Link>,
        },
      ];
    } else if (isTeacher) {
      return [
        {
          key: '/teacher',
          icon: <DashboardOutlined />,
          label: <Link to="/teacher">Dashboard</Link>,
        },
        {
          key: '/teacher/schedule',
          icon: <CalendarOutlined />,
          label: <Link to="/teacher/schedule">Teaching Schedule</Link>,
        },
        {
          key: '/teacher/attendance',
          icon: <TeamOutlined />,
          label: <Link to="/teacher/attendance">Attendance</Link>,
        },
      ];
    }
    return [];
  };

  return (
    <Layout style={{ minHeight: '100vh' }}>
      <Sider
        trigger={null}
        collapsible
        collapsed={collapsed}
        theme="dark"
        width={250}
        style={{
          boxShadow: '2px 0 8px 0 rgba(29,35,41,.05)',
          position: 'sticky',
          top: 0,
          height: '100vh',
        }}
      >
        <div
          style={{
            height: 64,
            margin: 16,
            display: 'flex',
            alignItems: 'center',
            justifyContent: collapsed ? 'center' : 'flex-start',
            gap: 12,
          }}
        >
          <Avatar
            size={40}
            src="/logo.png"
            icon={<BookOutlined />}
            style={{ backgroundColor: '#1890ff' }}
          />
          {!collapsed && (
            <span
              style={{
                color: '#fff',
                fontSize: 18,
                fontWeight: 700,
                letterSpacing: '0.5px',
              }}
            >
              SmartEdu
            </span>
          )}
        </div>
        <Menu
          theme="dark"
          mode="inline"
          selectedKeys={[location.pathname]}
          items={getMenuItems()}
          style={{ borderRight: 0, fontSize: '15px' }}
        />
      </Sider>
      <Layout>
        <Header
          style={{
            padding: '0 24px',
            background: colorBgContainer,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            boxShadow: '0 1px 4px rgba(0,21,41,.08)',
            zIndex: 1,
            position: 'sticky',
            top: 0,
          }}
        >
          <Button
            type="text"
            icon={collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />}
            onClick={() => setCollapsed(!collapsed)}
            style={{
              fontSize: '16px',
              width: 64,
              height: 64,
            }}
          />
          <div style={{ display: 'flex', alignItems: 'center', gap: 20 }}>
            <Popover
              content={notificationContent}
              trigger="click"
              placement="bottomRight"
              arrow={{ pointAtCenter: true }}
            >
              <Badge count={unreadCount} overflowCount={99} size="small">
                <Button type="text" shape="circle" icon={<BellOutlined />} />
              </Badge>
            </Popover>
            <div
              onClick={handleOpenProfileModal}
              style={{ display: 'flex', alignItems: 'center', gap: 10, cursor: 'pointer' }}
            >
              <Avatar src={user?.avatarUrl} icon={<UserOutlined />} style={{ backgroundColor: '#87d068' }} />
              <div style={{ display: 'flex', flexDirection: 'column', lineHeight: '1.2' }}>
                <span style={{ fontWeight: 600, fontSize: 14 }}>{user?.fullName || user?.email}</span>
                <span style={{ fontSize: 11, color: '#8c8c8c' }}>
                  {isAdmin ? 'Administrator' : isTeacher ? 'Teacher' : 'Student'}
                </span>
              </div>
            </div>
            <Popconfirm
              title="Logout"
              description="Are you sure you want to log out?"
              onConfirm={handleLogout}
              okText="Yes"
              cancelText="No"
              placement="bottomRight"
            >
              <Button
                type="primary"
                danger
                ghost
                icon={<LogoutOutlined />}
                size="small"
              >
                Logout
              </Button>
            </Popconfirm>
          </div>
        </Header>
        <Content
          style={{
            margin: '24px 16px',
            padding: 24,
            minHeight: 280,
            background: colorBgContainer,
            borderRadius: borderRadiusLG,
            overflowY: 'auto',
          }}
        >
          <Outlet />
        </Content>
      </Layout>

      <Modal
        title="Edit Profile"
        open={profileModalOpen}
        onOk={handleProfileSubmit}
        onCancel={() => setProfileModalOpen(false)}
        okText="Save Changes"
        destroyOnClose
      >
        <Form form={profileForm} layout="vertical" style={{ marginTop: 20 }}>
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', marginBottom: 20 }}>
            <Avatar size={80} src={avatarPreview} icon={<UserOutlined />} style={{ marginBottom: 12 }} />
            <Button icon={<UploadOutlined />} loading={uploading} style={{ position: 'relative', overflow: 'hidden' }}>
              Upload Avatar
              <input
                type="file"
                accept="image/*"
                onChange={handleAvatarChange}
                style={{
                  position: 'absolute',
                  top: 0,
                  right: 0,
                  margin: 0,
                  padding: 0,
                  fontSize: '20px',
                  cursor: 'pointer',
                  opacity: 0,
                  filter: 'alpha(opacity=0)',
                  height: '100%',
                  width: '100%',
                }}
              />
            </Button>
          </div>

          <Form.Item name="avatarUrl" style={{ display: 'none' }}>
            <Input />
          </Form.Item>

          <Form.Item
            name="fullName"
            label="Full Name"
            rules={[{ required: true, message: 'Please enter your full name!' }]}
          >
            <Input />
          </Form.Item>

          <Form.Item name="phone" label="Phone">
            <Input />
          </Form.Item>

          <Form.Item name="password" label="New Password (optional)">
            <Input.Password placeholder="Leave blank to keep current password" />
          </Form.Item>
        </Form>
      </Modal>
    </Layout>
  );
};

// new-client-app/src/app/pages/layout/dashboard-layout.component.ts
import { Component, signal, computed, effect } from '@angular/core';
import { Router, RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { AuthService } from '../../core/services/auth.service';
import { NotificationService } from '../../core/services/notification.service';
import { NotificationDto, ApiResponse } from '../../core/models';

@Component({
  selector: 'app-dashboard-layout',
  standalone: true,
  imports: [CommonModule, RouterOutlet, RouterLink, RouterLinkActive, FormsModule],
  templateUrl: './dashboard-layout.component.html',
  styleUrl: './dashboard-layout.component.css'
})
export class DashboardLayoutComponent {
  collapsed = signal<boolean>(false);
  showNotifications = signal<boolean>(false);
  profileModalOpen = signal<boolean>(false);
  uploading = signal<boolean>(false);
  profileError = signal<string | null>(null);

  notifications = signal<NotificationDto[]>([]);
  unreadCount = computed(() => this.notifications().filter(n => !n.isRead).length);

  user = computed(() => this.authService.currentUser());
  roleName = computed(() => {
    const u = this.user();
    if (!u) return '';
    if (u.roles.includes('Admin')) return 'Administrator';
    if (u.roles.includes('Teacher')) return 'Teacher';
    if (u.roles.includes('Student')) return 'Student';
    return '';
  });

  isAdmin = computed(() => this.user()?.roles.includes('Admin') ?? false);
  isTeacher = computed(() => this.user()?.roles.includes('Teacher') ?? false);
  isStudent = computed(() => this.user()?.roles.includes('Student') ?? false);

  avatarPreview = signal<string>('');
  profileValues = {
    fullName: '',
    phone: '',
    password: '',
    avatarUrl: ''
  };

  private pollInterval: any;

  constructor(
    private authService: AuthService,
    private notificationService: NotificationService,
    private router: Router,
    private http: HttpClient
  ) {
    // Synchronize profile values when user loads
    effect(() => {
      const u = this.user();
      if (u) {
        this.profileValues.fullName = u.fullName || '';
        this.profileValues.phone = u.phone || '';
        this.profileValues.avatarUrl = u.avatarUrl || '';
      }
    });

    // Start notification polling
    this.fetchNotifications();
    this.pollInterval = setInterval(() => this.fetchNotifications(), 15000);
  }

  ngOnDestroy() {
    if (this.pollInterval) {
      clearInterval(this.pollInterval);
    }
  }

  toggleSidebar() {
    this.collapsed.update(v => !v);
  }

  toggleNotifications() {
    this.showNotifications.update(v => !v);
  }

  fetchNotifications() {
    const u = this.user();
    if (!u) return;

    if (this.isStudent() && u.studentId) {
      this.notificationService.getByStudent(u.studentId).subscribe({
        next: data => this.notifications.set(data),
        error: () => console.log('Error fetching notifications')
      });
    } else if (this.isTeacher() && u.teacherId) {
      this.notificationService.getByTeacher(u.teacherId).subscribe({
        next: data => this.notifications.set(data),
        error: () => console.log('Error fetching notifications')
      });
    }
  }

  markAsRead(id: number) {
    this.notificationService.markAsRead(id).subscribe({
      next: () => {
        this.notifications.update(list => list.map(n => n.id === id ? { ...n, isRead: true } : n));
      },
      error: () => alert('Không thể đánh dấu đã đọc')
    });
  }

  markAllAsRead() {
    const unread = this.notifications().filter(n => !n.isRead);
    if (unread.length === 0) return;

    const requests = unread.map(n => this.notificationService.markAsRead(n.id).toPromise());
    Promise.all(requests)
      .then(() => {
        this.notifications.update(list => list.map(n => ({ ...n, isRead: true })));
      })
      .catch(() => alert('Thao tác thất bại'));
  }

  onAvatarError(event: any) {
    event.target.src = 'https://cdn-icons-png.flaticon.com/512/149/149071.png';
  }

  onPreviewAvatarError(event: any) {
    event.target.src = 'https://cdn-icons-png.flaticon.com/512/149/149071.png';
  }

  formatSentAt(dateStr: string): string {
    if (!dateStr) return '';
    try {
      const d = new Date(dateStr);
      return `${d.getHours().toString().padStart(2, '0')}:${d.getMinutes().toString().padStart(2, '0')} ${d.getDate().toString().padStart(2, '0')}/${(d.getMonth() + 1).toString().padStart(2, '0')}`;
    } catch {
      return dateStr;
    }
  }

  openProfileModal() {
    const u = this.user();
    this.avatarPreview.set(u?.avatarUrl || '');
    this.profileValues = {
      fullName: u?.fullName || '',
      phone: u?.phone || '',
      password: '',
      avatarUrl: u?.avatarUrl || ''
    };
    this.profileError.set(null);
    this.profileModalOpen.set(true);
  }

  closeProfileModal() {
    this.profileModalOpen.set(false);
  }

  handleAvatarUpload(event: any) {
    const file = event.target.files?.[0];
    if (!file) return;

    const formData = new FormData();
    formData.append('file', file);

    this.uploading.set(true);
    this.http.post<ApiResponse<string>>('/api/upload', formData).subscribe({
      next: res => {
        this.uploading.set(false);
        if (res.success && res.data) {
          this.avatarPreview.set(res.data);
          this.profileValues.avatarUrl = res.data;
        } else {
          alert('Upload failed: ' + res.message);
        }
      },
      error: () => {
        this.uploading.set(false);
        alert('Tải ảnh đại diện lên thất bại');
      }
    });
  }

  saveProfileChanges() {
    if (!this.profileValues.fullName.trim()) {
      this.profileError.set('Họ tên không được để trống');
      return;
    }

    this.authService.updateProfile(this.profileValues).subscribe({
      next: res => {
        if (res.success && res.data) {
          alert('Hồ sơ của bạn đã được cập nhật thành công');
          this.closeProfileModal();
        } else {
          this.profileError.set(res.message || 'Lỗi cập nhật');
        }
      },
      error: err => {
        this.profileError.set(err.error?.message || 'Không thể lưu thay đổi');
      }
    });
  }

  onLogout() {
    if (confirm('Bạn có chắc chắn muốn đăng xuất không?')) {
      this.authService.logout().subscribe({
        next: () => this.router.navigate(['/login']),
        error: () => this.router.navigate(['/login'])
      });
    }
  }
}

<div class="d-flex" style="min-height: 100vh; overflow-x: hidden;">
  <!-- Sidebar -->
  <aside class="bg-white border-end d-flex flex-column transition-all" 
         [style.width]="collapsed() ? '80px' : '260px'"
         style="height: 100vh; position: sticky; top: 0; transition: width 0.2s ease-in-out; z-index: 1000;">
    
    <!-- Logo Area -->
    <div class="p-4 text-center d-flex align-items-center justify-content-center" style="height: 100px;">
      <div class="rounded-circle d-inline-flex align-items-center justify-content-center text-white shadow-sm" 
           style="width: 48px; height: 48px; font-weight: bold; background-color: var(--primary-color);">
        SE
      </div>
      @if (!collapsed()) {
        <span class="ms-3 fw-bold fs-5 text-dark" style="letter-spacing: 0.5px;">SmartEdu</span>
      }
    </div>
    
    <!-- Navigation Links -->
    <div class="px-3 flex-grow-1 overflow-y-auto mt-2">
      <!-- Admin Menu -->
      @if (isAdmin()) {
        @if (!collapsed()) {
          <div class="text-uppercase text-muted fw-bold small px-3 mb-2" style="font-size: 11px; letter-spacing: 1px;">Tổng quan</div>
        }
        <a routerLink="/admin" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}" class="sidebar-link mb-1">
          <i class="bi bi-speedometer2 me-2"></i>
          @if (!collapsed()) { <span>Overview</span> }
        </a>
        @if (!collapsed()) {
          <div class="text-uppercase text-muted fw-bold small px-3 mt-3 mb-2" style="font-size: 11px; letter-spacing: 1px;">Quản lý</div>
        }
        <a routerLink="/admin/students" routerLinkActive="active" class="sidebar-link mb-1">
          <i class="bi bi-people me-2"></i>
          @if (!collapsed()) { <span>Students</span> }
        </a>
        <a routerLink="/admin/teachers" routerLinkActive="active" class="sidebar-link mb-1">
          <i class="bi bi-person-badge me-2"></i>
          @if (!collapsed()) { <span>Teachers</span> }
        </a>
        <a routerLink="/admin/courses" routerLinkActive="active" class="sidebar-link mb-1">
          <i class="bi bi-book me-2"></i>
          @if (!collapsed()) { <span>Courses</span> }
        </a>
        <a routerLink="/admin/classes" routerLinkActive="active" class="sidebar-link mb-1">
          <i class="bi bi-building me-2"></i>
          @if (!collapsed()) { <span>Classes</span> }
        </a>
        <a routerLink="/admin/reports" routerLinkActive="active" class="sidebar-link mb-1">
          <i class="bi bi-file-earmark-bar-graph me-2"></i>
          @if (!collapsed()) { <span>Reports</span> }
        </a>
      }
      
      <!-- Student Menu -->
      @if (isStudent()) {
        @if (!collapsed()) {
          <div class="text-uppercase text-muted fw-bold small px-3 mb-2" style="font-size: 11px; letter-spacing: 1px;">Student Center</div>
        }
        <a routerLink="/student" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}" class="sidebar-link mb-1">
          <i class="bi bi-grid-1x2 me-2"></i>
          @if (!collapsed()) { <span>Dashboard</span> }
        </a>
        <a routerLink="/student/schedule" routerLinkActive="active" class="sidebar-link mb-1">
          <i class="bi bi-calendar3 me-2"></i>
          @if (!collapsed()) { <span>Schedule</span> }
        </a>
        <a routerLink="/student/classes" routerLinkActive="active" class="sidebar-link mb-1">
          <i class="bi bi-mortarboard me-2"></i>
          @if (!collapsed()) { <span>My Classes</span> }
        </a>
        <a routerLink="/student/tuition" routerLinkActive="active" class="sidebar-link mb-1">
          <i class="bi bi-wallet2 me-2"></i>
          @if (!collapsed()) { <span>Tuition Wallet</span> }
        </a>
      }

      <!-- Teacher Menu -->
      @if (isTeacher()) {
        @if (!collapsed()) {
          <div class="text-uppercase text-muted fw-bold small px-3 mb-2" style="font-size: 11px; letter-spacing: 1px;">Teacher Center</div>
        }
        <a routerLink="/teacher" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}" class="sidebar-link mb-1">
          <i class="bi bi-grid-1x2 me-2"></i>
          @if (!collapsed()) { <span>Dashboard</span> }
        </a>
        <a routerLink="/teacher/schedule" routerLinkActive="active" class="sidebar-link mb-1">
          <i class="bi bi-calendar-event me-2"></i>
          @if (!collapsed()) { <span>Schedule</span> }
        </a>
        <a routerLink="/teacher/attendance" routerLinkActive="active" class="sidebar-link mb-1">
          <i class="bi bi-check2-square me-2"></i>
          @if (!collapsed()) { <span>Attendance</span> }
        </a>
      }
    </div>
    
    <!-- Logout at bottom -->
    <div class="p-3">
      <button (click)="onLogout()" class="btn w-100 border-0 d-flex align-items-center justify-content-center" 
              style="background-color: var(--primary-light); color: var(--primary-color); font-weight: 600; padding: 10px;">
        <i class="bi bi-box-arrow-right" [class.me-2]="!collapsed()"></i>
        @if (!collapsed()) { <span>Đăng xuất</span> }
      </button>
    </div>
  </aside>

  <!-- Main Content Container -->
  <div class="flex-grow-1 d-flex flex-column" style="background-color: var(--bg-app); min-height: 100vh; overflow-x: hidden;">
    <!-- Top Header -->
    <header class="bg-white border-bottom d-flex justify-content-between align-items-center px-4" 
            style="height: 70px; position: sticky; top: 0; z-index: 999; box-shadow: 0 1px 4px rgba(0,21,41,.04);">
      
      <button (click)="toggleSidebar()" class="btn border-0 p-2 text-muted hover-bg-light" style="font-size: 20px;">
        <i class="bi" [class.bi-list]="collapsed()" [class.bi-text-indent-left]="!collapsed()"></i>
      </button>
      
      <div class="d-flex align-items-center gap-3">
        <!-- Notifications Popover -->
        <div class="position-relative">
          <button (click)="toggleNotifications()" class="btn border-0 position-relative p-2 text-muted hover-bg-light" style="font-size: 18px;">
            <i class="bi bi-bell"></i>
            @if (unreadCount() > 0) {
              <span class="position-absolute translate-middle badge rounded-pill bg-danger" 
                    style="font-size: 10px; padding: 3px 6px; top: 8px; left: 28px;">
                {{ unreadCount() }}
              </span>
            }
          </button>
          
          <!-- Notifications Dropdown Box -->
          @if (showNotifications()) {
            <div class="position-absolute bg-white border rounded shadow-lg p-3" 
                 style="width: 320px; right: 0; top: 45px; z-index: 1100; max-height: 400px; overflow-y: auto;">
              <div class="d-flex justify-content-between align-items-center mb-2 pb-2 border-bottom">
                <span class="fw-bold">Thông báo</span>
                @if (unreadCount() > 0) {
                  <button (click)="markAllAsRead()" class="btn btn-link btn-sm text-decoration-none p-0">Đọc tất cả</button>
                }
              </div>
              
              @if (notifications().length === 0) {
                <div class="text-center py-4 text-muted">Không có thông báo nào</div>
              } @else {
                <div class="d-flex flex-column gap-2">
                  @for (item of notifications(); track item.id) {
                    <div class="p-2 rounded cursor-pointer transition-all"
                         [style.background-color]="item.isRead ? 'transparent' : '#f0f5ff'"
                         (click)="markAsRead(item.id)">
                      <div class="d-flex justify-content-between align-items-start">
                        <span class="fw-semibold text-dark text-truncate" style="font-size: 13px; max-width: 180px;">{{ item.title }}</span>
                        <span class="text-muted" style="font-size: 10px;">{{ formatSentAt(item.sentAt) }}</span>
                      </div>
                      <div class="text-muted mt-1" style="font-size: 11px; line-height: 1.3;">{{ item.message }}</div>
                    </div>
                  }
                </div>
              }
            </div>
          }
        </div>
        
        <!-- User Profile Dropdown -->
        <div class="d-flex align-items-center gap-2 cursor-pointer p-1 rounded hover-bg-light" 
             (click)="openProfileModal()">
          <img [src]="user()?.avatarUrl || 'assets/default-avatar.png'" 
               class="rounded-circle border" 
               style="width: 38px; height: 38px; object-fit: cover;" 
               alt="Avatar"
               (error)="onAvatarError($event)" />
          <div class="d-none d-md-flex flex-column text-start" style="line-height: 1.2;">
            <span class="fw-semibold text-dark" style="font-size: 13px;">{{ user()?.fullName || user()?.email }}</span>
            <span class="text-muted" style="font-size: 10px;">{{ roleName() }}</span>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Inner Content Area -->
    <main class="flex-grow-1 p-4">
      <router-outlet></router-outlet>
    </main>
  </div>
</div>

<!-- Edit Profile Modal -->
@if (profileModalOpen()) {
  <div class="modal fade show d-block" tabindex="-1" style="background-color: rgba(0,0,0,0.5); z-index: 1050;">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content border-0 shadow-lg" style="border-radius: 12px;">
        <div class="modal-header border-0 pb-0">
          <h5 class="modal-title fw-bold">Chỉnh sửa hồ sơ</h5>
          <button type="button" class="btn-close" (click)="closeProfileModal()"></button>
        </div>
        
        <div class="modal-body py-4">
          <div class="d-flex flex-column align-items-center mb-4">
            <img [src]="avatarPreview() || 'assets/default-avatar.png'" 
                 class="rounded-circle border mb-3" 
                 style="width: 90px; height: 90px; object-fit: cover;"
                 (error)="onPreviewAvatarError($event)" />
            <label class="btn btn-sm btn-secondary-light position-relative overflow-hidden cursor-pointer">
              @if (uploading()) {
                <span class="spinner-border spinner-border-sm me-1"></span> Đang tải...
              } @else {
                Tải ảnh lên
              }
              <input type="file" accept="image/*" class="position-absolute opacity-0" style="left: 0; top: 0; width:100%; height:100%; cursor: pointer;" (change)="handleAvatarUpload($event)" />
            </label>
          </div>

          @if (profileError()) {
            <div class="alert alert-danger py-2 px-3 text-center mb-3" style="font-size: 13px; border-radius: 8px;">{{ profileError() }}</div>
          }

          <div class="mb-3">
            <label class="form-label fw-semibold" style="font-size: 13px;">Họ tên</label>
            <input type="text" class="form-control" [(ngModel)]="profileValues.fullName" placeholder="Nhập họ tên" />
          </div>
          <div class="mb-3">
            <label class="form-label fw-semibold" style="font-size: 13px;">Số điện thoại</label>
            <input type="text" class="form-control" [(ngModel)]="profileValues.phone" placeholder="Nhập số điện thoại" />
          </div>
          <div class="mb-3">
            <label class="form-label fw-semibold" style="font-size: 13px;">Mật khẩu mới (tùy chọn)</label>
            <input type="password" class="form-control" [(ngModel)]="profileValues.password" placeholder="Bỏ trống nếu không muốn đổi" />
          </div>
        </div>
        
        <div class="modal-footer border-0 pt-0">
          <button type="button" class="btn btn-light" (click)="closeProfileModal()">Hủy</button>
          <button type="button" class="btn btn-primary" (click)="saveProfileChanges()">Lưu thay đổi</button>
        </div>
      </div>
    </div>
  </div>
}
