// client-app/src/pages/admin/Students.tsx
import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Table, Input, Button, Modal, Form, Select, DatePicker, Space, Tag, Popconfirm, message, Typography, Avatar, Row, Col, Card } from 'antd';
import { SearchOutlined, PlusOutlined, EditOutlined, DeleteOutlined, EyeOutlined, UploadOutlined, UserOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import dayjs from 'dayjs';
import { studentService } from '../../services';
import api from '../../services/api';

const { Option } = Select;
const { Title, Text } = Typography;

export const Students: React.FC = () => {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [form] = Form.useForm();
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);

  // Filter States
  const [keyword, setKeyword] = useState('');
  const [status, setStatus] = useState('');

  // Query Students
  const { data: students, isLoading } = useQuery({
    queryKey: ['students', keyword, status],
    queryFn: () => studentService.getAll({ search: keyword || undefined, status: status || undefined }),
  });

  // Mutation: Create Student
  const createMutation = useMutation({
    mutationFn: (newStudent: any) => studentService.create(newStudent),
    onSuccess: () => {
      message.success('Student created successfully');
      queryClient.invalidateQueries({ queryKey: ['students'] });
      setIsModalOpen(false);
      form.resetFields();
    },
    onError: (err: any) => {
      message.error(err.response?.data?.message || 'Failed to create student');
    },
  });

  // Mutation: Update Student
  const updateMutation = useMutation({
    mutationFn: ({ id, data }: { id: number; data: any }) => studentService.update(id, data),
    onSuccess: () => {
      message.success('Student updated successfully');
      queryClient.invalidateQueries({ queryKey: ['students'] });
      setIsModalOpen(false);
      form.resetFields();
      setEditingId(null);
    },
    onError: (err: any) => {
      message.error(err.response?.data?.message || 'Failed to update student');
    },
  });

  // Mutation: Delete Student
  const deleteMutation = useMutation({
    mutationFn: (id: number) => studentService.delete(id),
    onSuccess: () => {
      message.success('Student deleted successfully');
      queryClient.invalidateQueries({ queryKey: ['students'] });
    },
    onError: (err: any) => {
      message.error(err.response?.data?.message || 'Failed to delete student');
    },
  });

  const [avatarPreview, setAvatarPreview] = useState<string>('');
  const [uploading, setUploading] = useState(false);

  const handleOpenCreateModal = () => {
    setEditingId(null);
    setAvatarPreview('');
    form.resetFields();
    setIsModalOpen(true);
  };

  const handleOpenEditModal = (record: any) => {
    setEditingId(record.id);
    setAvatarPreview(record.avatarUrl || '');
    form.setFieldsValue({
      ...record,
      dateOfBirth: record.dateOfBirth ? dayjs(record.dateOfBirth) : null,
    });
    setIsModalOpen(true);
  };

  const handleAvatarChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const formData = new FormData();
    formData.append('file', file);

    setUploading(true);
    try {
      const res = await api.post('/upload', formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });
      const fileUrl = res.data.data;
      setAvatarPreview(fileUrl);
      form.setFieldsValue({ avatarUrl: fileUrl });
      message.success('Avatar uploaded successfully');
    } catch (err) {
      message.error('Failed to upload avatar');
    } finally {
      setUploading(false);
    }
  };

  const handleFormSubmit = () => {
    form.validateFields().then((values) => {
      const dataSubmit = {
        ...values,
        id: editingId || 0,
        dateOfBirth: values.dateOfBirth.format('YYYY-MM-DD'),
      };

      if (editingId) {
        updateMutation.mutate({ id: editingId, data: dataSubmit });
      } else {
        createMutation.mutate(dataSubmit);
      }
    });
  };

  const columns = [
    {
      title: 'Student ID',
      dataKey: 'studentCode',
      key: 'studentCode',
      render: (_: any, record: any) => <Text strong>{record.studentCode}</Text>,
    },
    {
      title: 'Full Name',
      key: 'fullName',
      render: (_: any, record: any) => (
        <Space>
          <Avatar src={record.avatarUrl} icon={<Avatar />} />
          <Text>{record.fullName}</Text>
        </Space>
      ),
    },
    {
      title: 'DOB',
      dataIndex: 'dateOfBirth',
      key: 'dateOfBirth',
      render: (date: string) => dayjs(date).format('YYYY-MM-DD'),
    },
    {
      title: 'Gender',
      dataIndex: 'gender',
      key: 'gender',
    },
    {
      title: 'Grade',
      dataIndex: 'gradeLevel',
      key: 'gradeLevel',
      render: (val: string) => <Tag color="blue">Grade {val}</Tag>,
    },
    {
      title: 'Parent Phone',
      dataIndex: 'parentPhone',
      key: 'parentPhone',
    },
    {
      title: 'Status',
      dataIndex: 'studentStatus',
      key: 'studentStatus',
      render: (val: string) => {
        const colorMap: Record<string, string> = { Active: 'green', Suspended: 'warning', Reserved: 'purple', Dropped: 'error' };
        return <Tag color={colorMap[val] ?? 'default'}>{val}</Tag>;
      },
    },
    {
      title: 'Action',
      key: 'action',
      render: (_: any, record: any) => (
        <Space size="middle">
          <Button
            type="primary"
            ghost
            icon={<EyeOutlined />}
            size="small"
            onClick={() => navigate(`/admin/students/${record.id}`)}
          >
            Details
          </Button>
          <Button
            icon={<EditOutlined />}
            size="small"
            onClick={() => handleOpenEditModal(record)}
          >
            Edit
          </Button>
          <Popconfirm
            title="Delete Student"
            description="Are you sure you want to delete this student profile?"
            onConfirm={() => deleteMutation.mutate(record.id)}
            okText="Yes"
            cancelText="No"
          >
            <Button type="primary" danger ghost icon={<DeleteOutlined />} size="small">
              Delete
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  const studentList = students ?? [];

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
        <div>
          <Title level={2} style={{ margin: 0, fontWeight: 700 }}>
            Student Management
          </Title>
          <Text type="secondary">Create, update, and manage student profiles and wallets.</Text>
        </div>
        <Button
          type="primary"
          icon={<PlusOutlined />}
          onClick={handleOpenCreateModal}
          size="large"
          style={{ borderRadius: 8 }}
        >
          Create A New Student
        </Button>
      </div>

      {/* Filters */}
      <Card style={{ marginBottom: 24, borderRadius: 8 }}>
        <Row gutter={[16, 16]}>
          <Col xs={24} sm={12} md={10}>
            <Input
              placeholder="Search by name, student code, phone, email..."
              prefix={<SearchOutlined />}
              value={keyword}
              onChange={(e) => setKeyword(e.target.value)}
              allowClear
              size="large"
            />
          </Col>
          <Col xs={24} sm={12} md={6}>
            <Select
              placeholder="Filter by status"
              value={status}
              onChange={(val) => setStatus(val)}
              style={{ width: '100%' }}
              size="large"
            >
              <Option value="">All Statuses</Option>
              <Option value="Active">Active</Option>
              <Option value="Suspended">Suspended</Option>
              <Option value="Reserved">Reserved</Option>
              <Option value="Dropped">Dropped</Option>
            </Select>
          </Col>
        </Row>
      </Card>

      {/* Data Table */}
      <Table
        columns={columns}
        dataSource={studentList}
        rowKey="id"
        loading={isLoading}
        pagination={{ pageSize: 10, showSizeChanger: true }}
        style={{ boxShadow: '0 4px 12px rgba(0,0,0,.03)' }}
      />

      {/* Create / Edit Modal */}
      <Modal
        title={editingId ? 'Update Student Profile' : 'Create New Student'}
        open={isModalOpen}
        onOk={handleFormSubmit}
        onCancel={() => setIsModalOpen(false)}
        width={800}
        okText={editingId ? 'Update' : 'Create'}
        destroyOnClose
      >
        <Form form={form} layout="vertical" style={{ marginTop: 20 }}>
          <Row gutter={16}>
            <Col xs={24} md={8}>
              <Form.Item
                name="studentCode"
                label="Student Code"
              >
                <Input placeholder="e.g. ST00001 (Leave blank to auto-generate)" disabled={!!editingId} />
              </Form.Item>
            </Col>
            <Col xs={24} md={8}>
              <Form.Item
                name="fullName"
                label="Full Name"
                rules={[{ required: true, message: 'Please enter full name!' }]}
              >
                <Input placeholder="Enter full name" />
              </Form.Item>
            </Col>
            <Col xs={24} md={8}>
              <Form.Item
                name="dateOfBirth"
                label="Date of Birth"
                rules={[{ required: true, message: 'Please select DOB!' }]}
              >
                <DatePicker style={{ width: '100%' }} />
              </Form.Item>
            </Col>
          </Row>

          <Row gutter={16}>
            <Col xs={24} md={8}>
              <Form.Item
                name="gender"
                label="Gender"
                rules={[{ required: true, message: 'Please select gender!' }]}
              >
                <Select placeholder="Select gender">
                  <Option value="Male">Male</Option>
                  <Option value="Female">Female</Option>
                  <Option value="Other">Other</Option>
                </Select>
              </Form.Item>
            </Col>
            <Col xs={24} md={8}>
              <Form.Item name="phone" label="Phone">
                <Input placeholder="Student phone" />
              </Form.Item>
            </Col>
            <Col xs={24} md={8}>
              <Form.Item
                name="email"
                label="Email"
                rules={[{ type: 'email', message: 'Enter a valid email!' }]}
              >
                <Input placeholder="Student email" />
              </Form.Item>
            </Col>
          </Row>

          <Row gutter={16}>
            <Col xs={24} md={24}>
              <Form.Item name="address" label="Address">
                <Input placeholder="Home address" />
              </Form.Item>
            </Col>
          </Row>

          <Row gutter={16}>
            <Col xs={24} md={6}>
              <Form.Item name="gradeLevel" label="Grade Level">
                <Input placeholder="e.g. 6" />
              </Form.Item>
            </Col>
            <Col xs={24} md={12}>
              <Form.Item name="schoolName" label="School Name">
                <Input placeholder="School name" />
              </Form.Item>
            </Col>
            <Col xs={24} md={6}>
              <Form.Item name="studentStatus" label="Status" initialValue="Active">
                <Select>
                  <Option value="Active">Active</Option>
                  <Option value="Suspended">Suspended</Option>
                  <Option value="Reserved">Reserved</Option>
                  <Option value="Dropped">Dropped</Option>
                </Select>
              </Form.Item>
            </Col>
          </Row>

          <Row gutter={16}>
            <Col xs={24} md={8}>
              <Form.Item name="parentName" label="Parent Name">
                <Input placeholder="Parent name" />
              </Form.Item>
            </Col>
            <Col xs={24} md={8}>
              <Form.Item name="parentPhone" label="Parent Phone">
                <Input placeholder="Parent contact phone" />
              </Form.Item>
            </Col>
            <Col xs={24} md={8}>
              <Form.Item name="parentEmail" label="Parent Email">
                <Input placeholder="Parent email" />
              </Form.Item>
            </Col>
          </Row>

          <Form.Item name="avatarUrl" label="Avatar" valuePropName="value">
            <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
              <Avatar size={48} src={avatarPreview} icon={<UserOutlined />} />
              <Button icon={<UploadOutlined />} loading={uploading} style={{ position: 'relative', overflow: 'hidden' }}>
                Upload Photo
                <input
                  type="file"
                  accept="image/*"
                  onChange={handleAvatarChange}
                  style={{
                    position: 'absolute',
                    top: 0,
                    right: 0,
                    margin: 0,
                    padding: 0,
                    fontSize: '20px',
                    cursor: 'pointer',
                    opacity: 0,
                    filter: 'alpha(opacity=0)',
                    height: '100%',
                    width: '100%',
                  }}
                />
              </Button>
            </div>
          </Form.Item>

          <Form.Item name="healthNote" label="Health / Special Notes">
            <Input.TextArea rows={2} placeholder="Any medical conditions or alerts" />
          </Form.Item>

          {!editingId && (
            <Form.Item name="password" label="Initial Password" rules={[{ required: true, message: 'Password required!' }]}>
              <Input.Password placeholder="Min 6 chars, upper + digit" />
            </Form.Item>
          )}
        </Form>
      </Modal>
    </div>
  );
};

// new-client-app/src/app/pages/admin/students/students.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule, FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { StudentService } from '../../../core/services/student.service';
import { StudentDto, ApiResponse } from '../../../core/models';

@Component({
  selector: 'app-students',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, FormsModule],
  templateUrl: './students.component.html',
  styleUrl: './students.component.css'
})
export class StudentsComponent implements OnInit {
  students = signal<StudentDto[]>([]);
  loading = signal<boolean>(true);
  modalOpen = signal<boolean>(false);
  editingId = signal<number | null>(null);
  uploading = signal<boolean>(false);
  submitError = signal<string | null>(null);

  // Filters
  keyword: string = '';
  status: string = '';

  studentForm!: FormGroup;
  avatarPreview = signal<string>('');

  constructor(
    private studentService: StudentService,
    private fb: FormBuilder,
    private router: Router,
    private http: HttpClient
  ) {}

  ngOnInit() {
    this.fetchStudents();
    this.initForm();
  }

  initForm() {
    this.studentForm = this.fb.group({
      studentCode: [''],
      fullName: ['', Validators.required],
      dateOfBirth: ['', Validators.required],
      gender: ['', Validators.required],
      phone: [''],
      email: ['', [Validators.email]],
      address: [''],
      gradeLevel: [''],
      schoolName: [''],
      studentStatus: ['Active'],
      parentName: [''],
      parentPhone: [''],
      parentEmail: [''],
      avatarUrl: [''],
      healthNote: [''],
      password: ['', Validators.required]
    });
  }

  fetchStudents() {
    this.loading.set(true);
    const params: any = {};
    if (this.keyword.trim()) params.search = this.keyword;
    if (this.status) params.status = this.status;

    this.studentService.getAll(params).subscribe({
      next: (list) => {
        this.students.set(list);
        this.loading.set(false);
      },
      error: (err) => {
        this.loading.set(false);
        console.error(err);
      }
    });
  }

  onFilterChange() {
    this.fetchStudents();
  }

  openCreateModal() {
    this.editingId.set(null);
    this.avatarPreview.set('');
    this.initForm();
    this.submitError.set(null);
    this.modalOpen.set(true);
  }

  openEditModal(student: any) {
    this.editingId.set(student.id);
    this.avatarPreview.set(student.avatarUrl || '');
    this.initForm();
    this.studentForm.removeControl('password'); // Remove password field when editing

    // Format DOB to YYYY-MM-DD
    let dob = '';
    if (student.dateOfBirth) {
      dob = student.dateOfBirth.split('T')[0];
    }

    this.studentForm.patchValue({
      ...student,
      dateOfBirth: dob
    });
    this.submitError.set(null);
    this.modalOpen.set(true);
  }

  closeModal() {
    this.modalOpen.set(false);
  }

  handleAvatarUpload(event: any) {
    const file = event.target.files?.[0];
    if (!file) return;

    const formData = new FormData();
    formData.append('file', file);

    this.uploading.set(true);
    this.http.post<ApiResponse<string>>('/api/upload', formData).subscribe({
      next: res => {
        this.uploading.set(false);
        if (res.success && res.data) {
          this.avatarPreview.set(res.data);
          this.studentForm.patchValue({ avatarUrl: res.data });
        } else {
          alert('Tải ảnh lên thất bại: ' + res.message);
        }
      },
      error: () => {
        this.uploading.set(false);
        alert('Có lỗi xảy ra khi tải ảnh lên.');
      }
    });
  }

  onSubmit() {
    if (this.studentForm.invalid) {
      this.studentForm.markAllAsTouched();
      return;
    }

    this.submitError.set(null);
    const dataSubmit = this.studentForm.value;

    if (this.editingId()) {
      this.studentService.update(this.editingId()!, dataSubmit).subscribe({
        next: () => {
          alert('Hồ sơ học sinh đã được cập nhật thành công');
          this.closeModal();
          this.fetchStudents();
        },
        error: err => {
          this.submitError.set(err.error?.message || 'Cập nhật thất bại. Vui lòng kiểm tra lại.');
        }
      });
    } else {
      this.studentService.create(dataSubmit).subscribe({
        next: () => {
          alert('Học sinh mới đã được thêm thành công');
          this.closeModal();
          this.fetchStudents();
        },
        error: err => {
          this.submitError.set(err.error?.message || 'Thêm học sinh thất bại. Vui lòng kiểm tra lại.');
        }
      });
    }
  }

  deleteStudent(id: number) {
    if (confirm('Bạn có chắc chắn muốn xóa hồ sơ học sinh này không?')) {
      this.studentService.delete(id).subscribe({
        next: (res) => {
          if (res.success) {
            alert('Học sinh đã được xóa thành công');
            this.fetchStudents();
          } else {
            alert(res.message || 'Xóa thất bại');
          }
        },
        error: (err) => {
          alert(err.error?.message || 'Không thể xóa học sinh này.');
        }
      });
    }
  }

  viewDetails(id: number) {
    this.router.navigate([`/admin/students/${id}`]);
  }

  getStatusClass(status: string): string {
    switch (status) {
      case 'Active': return 'success';
      case 'Suspended': return 'warning';
      case 'Reserved': return 'info';
      case 'Dropped': return 'danger';
      default: return '';
    }
  }

  formatDate(dateStr: string): string {
    if (!dateStr) return '';
    try {
      const d = new Date(dateStr);
      return `${d.getDate().toString().padStart(2, '0')}/${(d.getMonth() + 1).toString().padStart(2, '0')}/${d.getFullYear()}`;
    } catch {
      return dateStr;
    }
  }

  hasControlError(controlName: string, errorName: string): boolean {
    const control = this.studentForm.get(controlName);
    return !!(control && control.touched && control.hasError(errorName));
  }

  onAvatarError(event: any) {
    event.target.src = 'https://cdn-icons-png.flaticon.com/512/149/149071.png';
  }
}

<div>
  <!-- Header Area -->
  <div class="d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center gap-3 mb-4">
    <div>
      <h1 class="page-title mb-0">Học Sinh</h1>
      <p class="text-muted mb-0">Tạo, cập nhật và quản lý danh sách học sinh và ví học phí.</p>
    </div>
    <button (click)="openCreateModal()" class="btn btn-primary d-flex align-items-center gap-2">
      <i class="bi bi-plus-lg"></i> Thêm Học Sinh Mới
    </button>
  </div>

  <!-- Filters Section -->
  <div class="custom-card shadow-sm mb-4">
    <div class="row g-3">
      <div class="col-12 col-md-8 col-lg-9">
        <div class="input-group">
          <span class="input-group-text bg-white border-end-0 text-muted"><i class="bi bi-search"></i></span>
          <input type="text" class="form-control border-start-0 ps-0" 
                 placeholder="Tìm kiếm theo tên, mã học sinh, số điện thoại, email..." 
                 [(ngModel)]="keyword" (ngModelChange)="onFilterChange()" />
        </div>
      </div>
      <div class="col-12 col-md-4 col-lg-3">
        <select class="form-select" [(ngModel)]="status" (ngModelChange)="onFilterChange()">
          <option value="">Tất cả trạng thái</option>
          <option value="Active">Active</option>
          <option value="Suspended">Suspended</option>
          <option value="Reserved">Reserved</option>
          <option value="Dropped">Dropped</option>
        </select>
      </div>
    </div>
  </div>

  <!-- Table Section -->
  <div class="custom-card shadow-sm p-0 overflow-hidden">
    @if (loading()) {
      <div class="text-center py-5">
        <div class="spinner-border text-primary" role="status"></div>
        <div class="mt-2 text-muted">Đang tải danh sách học sinh...</div>
      </div>
    } @else if (students().length === 0) {
      <div class="text-center py-5 text-muted">
        <i class="bi bi-people" style="font-size: 40px;"></i>
        <p class="mt-2 mb-0">Không tìm thấy học sinh nào.</p>
      </div>
    } @else {
      <div class="table-responsive">
        <table class="table mb-0">
          <thead>
            <tr>
              <th>Mã học sinh</th>
              <th>Họ và tên</th>
              <th>Ngày sinh</th>
              <th>Giới tính</th>
              <th>Khối</th>
              <th>SĐT Phụ huynh</th>
              <th>Trạng thái</th>
              <th class="text-center">Thao tác</th>
            </tr>
          </thead>
          <tbody>
            @for (student of students(); track student.id) {
              <tr>
                <td><span class="fw-bold">{{ student.studentCode }}</span></td>
                <td>
                  <div class="d-flex align-items-center gap-2">
                    <img [src]="student.avatarUrl || 'https://cdn-icons-png.flaticon.com/512/149/149071.png'" 
                         class="rounded-circle border" 
                         style="width: 32px; height: 32px; object-fit: cover;" 
                         (error)="onAvatarError($event)" />
                    <span class="fw-semibold">{{ student.fullName }}</span>
                  </div>
                </td>
                <td>{{ formatDate(student.dateOfBirth) }}</td>
                <td>{{ student.gender }}</td>
                <td><span class="badge bg-primary-subtle text-primary border border-primary-subtle">Khối {{ student.gradeLevel }}</span></td>
                <td>{{ student.parentPhone }}</td>
                <td>
                  <span class="custom-badge" [ngClass]="getStatusClass(student.studentStatus)">
                    {{ student.studentStatus }}
                  </span>
                </td>
                <td>
                  <div class="d-flex justify-content-center gap-2">
                    <button (click)="viewDetails(student.id)" class="btn btn-outline-primary-custom d-flex align-items-center gap-1">
                      <i class="bi bi-eye"></i> Chi tiết
                    </button>
                    <button (click)="openEditModal(student)" class="btn btn-light border btn-sm" style="padding: 4px 10px;">
                      <i class="bi bi-pencil"></i> Sửa
                    </button>
                    <button (click)="deleteStudent(student.id)" class="btn btn-outline-danger-custom d-flex align-items-center gap-1">
                      <i class="bi bi-trash"></i> Xóa
                    </button>
                  </div>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    }
  </div>

  <!-- Add/Edit Modal -->
  @if (modalOpen()) {
    <div class="modal fade show d-block" tabindex="-1" style="background-color: rgba(0,0,0,0.5); z-index: 1050;">
      <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content border-0 shadow-lg" style="border-radius: 12px;">
          <div class="modal-header border-0 pb-0">
            <h5 class="modal-title fw-bold">
              {{ editingId() ? 'Cập Nhật Hồ Sơ Học Sinh' : 'Thêm Học Sinh Mới' }}
            </h5>
            <button type="button" class="btn-close" (click)="closeModal()"></button>
          </div>

          <div class="modal-body py-4">
            @if (submitError()) {
              <div class="alert alert-danger py-2 px-3 text-center mb-3" style="font-size: 13px; border-radius: 8px;">
                {{ submitError() }}
              </div>
            }

            <form [formGroup]="studentForm">
              <div class="row g-3">
                <!-- Student Code -->
                <div class="col-12 col-md-4">
                  <label class="form-label fw-semibold small">Mã học sinh</label>
                  <input type="text" class="form-control" formControlName="studentCode" 
                         placeholder="Tự động sinh nếu bỏ trống" [attr.disabled]="editingId() ? true : null" />
                </div>

                <!-- Full Name -->
                <div class="col-12 col-md-4">
                  <label class="form-label fw-semibold small">Họ và tên *</label>
                  <input type="text" class="form-control" formControlName="fullName" placeholder="Nhập họ và tên" />
                  @if (hasControlError('fullName', 'required')) {
                    <div class="text-danger small mt-1">Vui lòng điền họ tên!</div>
                  }
                </div>

                <!-- DOB -->
                <div class="col-12 col-md-4">
                  <label class="form-label fw-semibold small">Ngày sinh *</label>
                  <input type="date" class="form-control" formControlName="dateOfBirth" />
                  @if (hasControlError('dateOfBirth', 'required')) {
                    <div class="text-danger small mt-1">Vui lòng chọn ngày sinh!</div>
                  }
                </div>

                <!-- Gender -->
                <div class="col-12 col-md-4">
                  <label class="form-label fw-semibold small">Giới tính *</label>
                  <select class="form-select" formControlName="gender">
                    <option value="">Chọn giới tính</option>
                    <option value="Male">Nam</option>
                    <option value="Female">Nữ</option>
                    <option value="Other">Khác</option>
                  </select>
                  @if (hasControlError('gender', 'required')) {
                    <div class="text-danger small mt-1">Vui lòng chọn giới tính!</div>
                  }
                </div>

                <!-- Phone -->
                <div class="col-12 col-md-4">
                  <label class="form-label fw-semibold small">Số điện thoại</label>
                  <input type="text" class="form-control" formControlName="phone" placeholder="SĐT học sinh" />
                </div>

                <!-- Email -->
                <div class="col-12 col-md-4">
                  <label class="form-label fw-semibold small">Email</label>
                  <input type="email" class="form-control" formControlName="email" placeholder="Email học sinh" />
                  @if (hasControlError('email', 'email')) {
                    <div class="text-danger small mt-1">Email không đúng định dạng!</div>
                  }
                </div>

                <!-- Address -->
                <div class="col-12">
                  <label class="form-label fw-semibold small">Địa chỉ</label>
                  <input type="text" class="form-control" formControlName="address" placeholder="Địa chỉ nhà" />
                </div>

                <!-- Grade -->
                <div class="col-12 col-md-4">
                  <label class="form-label fw-semibold small">Khối lớp (e.g. 6)</label>
                  <input type="text" class="form-control" formControlName="gradeLevel" placeholder="Khối lớp" />
                </div>

                <!-- School -->
                <div class="col-12 col-md-5">
                  <label class="form-label fw-semibold small">Trường học</label>
                  <input type="text" class="form-control" formControlName="schoolName" placeholder="Tên trường học" />
                </div>

                <!-- Status -->
                <div class="col-12 col-md-3">
                  <label class="form-label fw-semibold small">Trạng thái</label>
                  <select class="form-select" formControlName="studentStatus">
                    <option value="Active">Active</option>
                    <option value="Suspended">Suspended</option>
                    <option value="Reserved">Reserved</option>
                    <option value="Dropped">Dropped</option>
                  </select>
                </div>

                <!-- Parent Name -->
                <div class="col-12 col-md-4">
                  <label class="form-label fw-semibold small">Tên phụ huynh</label>
                  <input type="text" class="form-control" formControlName="parentName" placeholder="Họ tên phụ huynh" />
                </div>

                <!-- Parent Phone -->
                <div class="col-12 col-md-4">
                  <label class="form-label fw-semibold small">SĐT phụ huynh</label>
                  <input type="text" class="form-control" formControlName="parentPhone" placeholder="SĐT phụ huynh" />
                </div>

                <!-- Parent Email -->
                <div class="col-12 col-md-4">
                  <label class="form-label fw-semibold small">Email phụ huynh</label>
                  <input type="email" class="form-control" formControlName="parentEmail" placeholder="Email phụ huynh" />
                </div>

                <!-- Image Upload -->
                <div class="col-12">
                  <label class="form-label fw-semibold small">Ảnh đại diện</label>
                  <div class="d-flex align-items-center gap-3">
                    <img [src]="avatarPreview() || 'https://cdn-icons-png.flaticon.com/512/149/149071.png'" 
                         class="rounded-circle border" 
                         style="width: 50px; height: 50px; object-fit: cover;"
                         (error)="onAvatarError($event)" />
                    <label class="btn btn-sm btn-secondary-light position-relative overflow-hidden cursor-pointer">
                      @if (uploading()) {
                        <span class="spinner-border spinner-border-sm me-1"></span> Đang tải...
                      } @else {
                        Tải ảnh lên
                      }
                      <input type="file" accept="image/*" class="position-absolute opacity-0" 
                             style="left:0; top:0; width:100%; height:100%; cursor:pointer;" 
                             (change)="handleAvatarUpload($event)" />
                    </label>
                  </div>
                </div>

                <!-- Health Note -->
                <div class="col-12">
                  <label class="form-label fw-semibold small">Ghi chú sức khỏe / đặc biệt</label>
                  <textarea class="form-control" formControlName="healthNote" rows="2" 
                            placeholder="Các lưu ý về bệnh lý hoặc ghi chú khác"></textarea>
                </div>

                <!-- Password (only for creation) -->
                @if (!editingId()) {
                  <div class="col-12">
                    <label class="form-label fw-semibold small">Mật khẩu khởi tạo *</label>
                    <input type="password" class="form-control" formControlName="password" 
                           placeholder="Tối thiểu 6 ký tự, gồm chữ hoa + số" />
                    @if (hasControlError('password', 'required')) {
                      <div class="text-danger small mt-1">Vui lòng nhập mật khẩu khởi tạo!</div>
                    }
                  </div>
                }
              </div>
            </form>
          </div>

          <div class="modal-footer border-0 pt-0">
            <button type="button" class="btn btn-light" (click)="closeModal()">Hủy</button>
            <button type="button" class="btn btn-primary" (click)="onSubmit()" 
                    [disabled]="studentForm.invalid || uploading()">
              {{ editingId() ? 'Lưu thay đổi' : 'Thêm mới' }}
            </button>
          </div>
        </div>
      </div>
    </div>
  }
</div>
