// new-client-app/src/app/pages/login/login.component.ts
import { Component, signal } from '@angular/core';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {
  loginForm: FormGroup;
  loading = signal<boolean>(false);
  errorMessage = signal<string | null>(null);

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required]]
    });
  }

  onSubmit() {
    if (this.loginForm.invalid) return;

    this.loading.set(true);
    this.errorMessage.set(null);

    this.authService.login(this.loginForm.value).subscribe({
      next: (res) => {
        this.loading.set(false);
        if (res.success && res.data) {
          const roles = res.data.user.roles || [];
          if (roles.includes('Admin')) {
            this.router.navigate(['/admin']);
          } else if (roles.includes('Student')) {
            this.router.navigate(['/student']);
          } else if (roles.includes('Teacher')) {
            this.router.navigate(['/teacher']);
          } else {
            this.errorMessage.set('Tài khoản của bạn không có quyền truy cập.');
            this.authService.clearAuth();
          }
        } else {
          this.errorMessage.set(res.message || 'Đăng nhập thất bại.');
        }
      },
      error: (err) => {
        this.loading.set(false);
        const errMsg = err.error?.message || 'Email hoặc mật khẩu không hợp lệ. Vui lòng thử lại.';
        this.errorMessage.set(errMsg);
      }
    });
  }
}

<div class="d-flex align-items-center justify-content-center min-vh-100 px-3" 
     style="background: linear-gradient(135deg, #1e3a8a 0%, #0d9488 100%);">
  
  <div class="card w-100 shadow-lg border-0 p-4" style="max-width: 420px; border-radius: 16px;">
    <div class="text-center mb-4">
      <div class="d-inline-flex align-items-center justify-content-center text-primary mb-2">
        <i class="bi bi-book-half" style="font-size: 38px; color: var(--primary-color);"></i>
      </div>
      <h2 class="fw-bold mb-1" style="color: #212529;">SmartEdu</h2>
      <p class="text-muted small">Student Management & Tuition Wallet System</p>
    </div>

    @if (errorMessage()) {
      <div class="alert alert-danger d-flex align-items-center gap-2 py-2 px-3 mb-4" style="border-radius: 8px; font-size: 13px;">
        <i class="bi bi-exclamation-triangle-fill"></i>
        <div>{{ errorMessage() }}</div>
      </div>
    }

    <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
      <!-- Email Address -->
      <div class="mb-3">
        <label class="form-label fw-semibold text-muted small">Email Address</label>
        <div class="input-group">
          <span class="input-group-text bg-white border-end-0 text-muted"><i class="bi bi-envelope"></i></span>
          <input type="email" class="form-control border-start-0 ps-0" 
                 formControlName="email" placeholder="email@example.com" />
        </div>
        @if (loginForm.get('email')?.touched && loginForm.get('email')?.hasError('required')) {
          <div class="text-danger small mt-1">Please enter your email!</div>
        }
        @if (loginForm.get('email')?.touched && loginForm.get('email')?.hasError('email')) {
          <div class="text-danger small mt-1">Please enter a valid email address!</div>
        }
      </div>

      <!-- Password -->
      <div class="mb-4">
        <label class="form-label fw-semibold text-muted small">Password</label>
        <div class="input-group">
          <span class="input-group-text bg-white border-end-0 text-muted"><i class="bi bi-lock"></i></span>
          <input type="password" class="form-control border-start-0 ps-0" 
                 formControlName="password" placeholder="Password" />
        </div>
        @if (loginForm.get('password')?.touched && loginForm.get('password')?.hasError('required')) {
          <div class="text-danger small mt-1">Please enter your password!</div>
        }
      </div>

      <!-- Sign In Button -->
      <button type="submit" class="btn btn-primary w-100 py-2.5 mb-3" 
              [disabled]="loginForm.invalid || loading()" 
              style="border-radius: 8px; font-weight: 600; font-size: 15px; height: 48px; background-color: var(--primary-color);">
        @if (loading()) {
          <span class="spinner-border spinner-border-sm me-2"></span> Đang đăng nhập...
        } @else {
          Sign In
        }
      </button>
    </form>

    <div class="text-center mt-3 p-3 bg-light rounded-3" style="font-size: 12.5px; border: 1px solid var(--border-color);">
      <span class="text-muted">Demo accounts:</span>
      <div class="mt-2 text-start">
        <div class="d-flex justify-content-between mb-1">
          <code>admin&#64;smartedu.local</code>
          <span class="text-muted">pw: <code>Admin&#64;123</code></span>
        </div>
        <div class="d-flex justify-content-between mb-1">
          <code>teacher&#64;smartedu.local</code>
          <span class="text-muted">pw: <code>Teacher&#64;123</code></span>
        </div>
        <div class="d-flex justify-content-between">
          <code>student&#64;smartedu.local</code>
          <span class="text-muted">pw: <code>Student&#64;123</code></span>
        </div>
      </div>
    </div>
  </div>

</div>

// client-app/src/pages/Login.tsx
import React, { useState } from 'react';
import { Form, Input, Button, Card, Typography, Alert, Space } from 'antd';
import { UserOutlined, LockOutlined, BookOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import { useAppDispatch } from '../hooks/redux';
import { setCredentials } from '../store/authSlice';
import api from '../services/api';

const { Title, Text } = Typography;

export const Login: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const navigate = useNavigate();
  const dispatch = useAppDispatch();

  const onFinish = async (values: any) => {
    setLoading(true);
    setError(null);
    try {
      const response = await api.post('/auth/login', {
        email: values.email,
        password: values.password,
      });

      const { data } = response.data;
      localStorage.setItem('accessToken', data.accessToken);
      localStorage.setItem('refreshToken', data.refreshToken);
      dispatch(setCredentials({
        accessToken: data.accessToken,
        refreshToken: data.refreshToken,
        user: data.user,
      }));

      // Redirect based on role
      const roles = data.user.roles || [];
      if (roles.includes('Admin')) {
        navigate('/admin');
      } else if (roles.includes('Student')) {
        navigate('/student');
      } else if (roles.includes('Teacher')) {
        navigate('/teacher');
      } else {
        setError('Unauthorized role');
      }
    } catch (err: any) {
      console.error(err);
      const errMsg = err.response?.data?.message || 'Invalid email or password. Please try again.';
      setError(errMsg);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div
      style={{
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        minHeight: '100vh',
        background: 'linear-gradient(135deg, #1e3a8a 0%, #0d9488 100%)',
        padding: '20px',
      }}
    >
      <Card
        style={{
          width: '100%',
          maxWidth: 420,
          borderRadius: 16,
          boxShadow: '0 10px 25px rgba(0, 0, 0, 0.15)',
        }}
      >
        <div style={{ textAlign: 'center', marginBottom: 24 }}>
          <Space align="center" style={{ marginBottom: 12 }}>
            <BookOutlined style={{ fontSize: 32, color: '#1890ff' }} />
            <Title level={2} style={{ margin: 0, fontWeight: 700 }}>
              SmartEdu
            </Title>
          </Space>
          <div>
            <Text type="secondary">Student Management & Tuition Wallet System</Text>
          </div>
        </div>

        {error && (
          <Alert
            message={error}
            type="error"
            showIcon
            style={{ marginBottom: 20, borderRadius: 8 }}
          />
        )}

        <Form
          name="login"
          initialValues={{ remember: true }}
          onFinish={onFinish}
          layout="vertical"
          size="large"
        >
          <Form.Item
            name="email"
            rules={[
              { required: true, message: 'Please enter your email!' },
              { type: 'email', message: 'Please enter a valid email address!' },
            ]}
          >
            <Input
              prefix={<UserOutlined style={{ color: '#bfbfbf' }} />}
              placeholder="Email address"
            />
          </Form.Item>

          <Form.Item
            name="password"
            rules={[{ required: true, message: 'Please enter your password!' }]}
          >
            <Input.Password
              prefix={<LockOutlined style={{ color: '#bfbfbf' }} />}
              placeholder="Password"
            />
          </Form.Item>

          <Form.Item style={{ marginBottom: 10 }}>
            <Button
              type="primary"
              htmlType="submit"
              loading={loading}
              style={{
                width: '100%',
                borderRadius: 8,
                fontWeight: 600,
                height: 48,
              }}
            >
              Sign In
            </Button>
          </Form.Item>
        </Form>

        <div style={{ marginTop: 20, textAlign: 'center', fontSize: '13px' }}>
          <Text type="secondary">Demo accounts: </Text>
          <div style={{ marginTop: 5 }}>
            <Text code>admin@smartedu.local</Text> (pw: <Text code>Admin@123</Text>)<br />
            <Text code>teacher@smartedu.local</Text> (pw: <Text code>Teacher@123</Text>)<br />
            <Text code>student@smartedu.local</Text> (pw: <Text code>Student@123</Text>)
          </div>
        </div>
      </Card>
    </div>
  );
};
